// <auto-generated />
namespace SolarOrderQuiz.Resources
{
    using System.Reflection;
    using System.Resources;
    using System.Globalization;

    public static class Strings
    {
        private static readonly ResourceManager resourceManager = new ResourceManager("SolarOrderQuiz.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);

        public static string Get(string key) => resourceManager.GetString(key, CultureInfo.CurrentUICulture) ?? string.Empty;

        public static string AppTitle => Get(nameof(AppTitle));
        public static string PlanetPaletteTitle => Get(nameof(PlanetPaletteTitle));
        public static string OrbitAreaTitle => Get(nameof(OrbitAreaTitle));
        public static string StatusPanelTitle => Get(nameof(StatusPanelTitle));
        public static string RemainingPlanets => Get(nameof(RemainingPlanets));
        public static string CorrectAnswers => Get(nameof(CorrectAnswers));
        public static string IncorrectAnswers => Get(nameof(IncorrectAnswers));
        public static string Score => Get(nameof(Score));
        public static string Time => Get(nameof(Time));
        public static string Reset => Get(nameof(Reset));
        public static string Retry => Get(nameof(Retry));
        public static string SummaryTitle => Get(nameof(SummaryTitle));
        public static string SummaryDescription => Get(nameof(SummaryDescription));
        public static string SummaryCorrect => Get(nameof(SummaryCorrect));
        public static string SummaryIncorrect => Get(nameof(SummaryIncorrect));
        public static string SummaryTime => Get(nameof(SummaryTime));
        public static string SummaryScore => Get(nameof(SummaryScore));
        public static string SummaryBonus => Get(nameof(SummaryBonus));
        public static string Continue => Get(nameof(Continue));
        public static string Confirm => Get(nameof(Confirm));
        public static string QuestionTitleFormat => Get(nameof(QuestionTitleFormat));
        public static string CorrectAnswerFeedback => Get(nameof(CorrectAnswerFeedback));
        public static string IncorrectAnswerFeedback => Get(nameof(IncorrectAnswerFeedback));
        public static string Load => Get(nameof(Load));
        public static string Save => Get(nameof(Save));
        public static string LoadSuccess => Get(nameof(LoadSuccess));
        public static string LoadFailed => Get(nameof(LoadFailed));
        public static string SaveSuccess => Get(nameof(SaveSuccess));
        public static string SaveFailed => Get(nameof(SaveFailed));
        public static string SummaryRetry => Get(nameof(SummaryRetry));
        public static string SummaryClose => Get(nameof(SummaryClose));
        public static string PaletteTooltip => Get(nameof(PaletteTooltip));
        public static string OrbitTooltip => Get(nameof(OrbitTooltip));
        public static string SummaryAccuracy => Get(nameof(SummaryAccuracy));
        public static string OrbitOccupiedMessage => Get(nameof(OrbitOccupiedMessage));
        public static string OrbitMismatchMessage => Get(nameof(OrbitMismatchMessage));

    }
}
